sudo: false

language: python

python: 2.7

before_install:
  - pip install -r requirements.txt

install:
  - python setup.py install

before_script:
  - pip install -q nose hacking

script:
  - flake8 pycd
  - nosetests

after_success:
  - coveralls
